const filteredMainCategories = {
	fastfood: [],
	'resto/bar': [],
	courses: [],
	'abonnements/telephonie': ['Abonnements & téléphonie'],
	ecole: ['Education & Famille'],
	transports: [],
	voyages: ['Voyages & Transports'],
	sante: ['Santé'],
	revenus: [
		'Pensions & rentes',
		'Revenus du travail',
		'Virements reçus',
		"Revenus d'épargne",
		'Remboursement de frais / offres Boursorama',
	],
	remboursements: ['Remboursements'],
	mouvements_internes: ["Dépenses d'épargne", 'Mouvements internes débiteurs', 'Mouvements internes créditeurs'],
	impots: ['Impôts'],
	vie_quotidienne: ['Vie quotidienne'],
	amendes: [],
	voiture: ['Auto & Moto'],
	cadeaux: ['Cadeaux et solidarité'],
	ecommerce: [],
	vetements: [],
	maison: ['Logement'],
	activites: ['Loisirs'],
	banque: [
		'Services financiers & professionnels',
		'Emprunts (hors immobilier)',
		'Retraits cash',
		'Dépots (cartes/chéques/espèces)',
	],
	autres: ['Non catégorisé', 'Virements émis'],
};

const filteredCategories = {
	fastfood: [],
	'resto/bar': ['Restaurants, bars, discothèques…'],
	courses: ['Alimentation'],
	'abonnements/telephonie': [],
	ecole: [],
	transports: ['Transports quotidiens (métro, bus…)', 'Location de véhicules'],
	voyages: [],
	sante: [],
	revenus: [],
	remboursements: ['Remboursements frais de vie quotidienne', 'Remboursements - Autres'],
	mouvements_internes: [],
	impots: [],
	vie_quotidienne: [],
	amendes: ['Contraventions'],
	voiture: [],
	cadeaux: [],
	ecommerce: ['Electronique et informatique'],
	vetements: ['Vêtements et accessoires'],
	maison: ['Mobilier, électroménager, décoration…'],
	activites: [],
	banque: [],
	autres: [],
};

const filteredLabels = {
	fastfood: [
		"mcdonald's",
		'mcdo',
		'macdo',
		'kfc',
		'sc.rest cirha', // domino's clamart
		'burger king',
		'bk',
		'quick',
		'subway',
		'pizza hut',
		'pizzahut',
		'pizza',
	],
	'resto/bar': [
		'lydia',
		'okali', // lydia
		'55amsterd',
	],
	courses: [
		'carrefour',
		'monoprix',
		'super u',
		'intermarché',
		'leclerc',
		'franprix',
		'lidl',
		'aldi',
		'picard',
		'casino',
		'auchan',
		'cora',
		'biocoop',
		'bio c bon',
	],
	'abonnements/telephonie': ['nordvpn', 'netflix', 'spotify', 'deezer', 'bouygues', 'orange', 'sfr', 'free'],
	ecole: ['efrei', 'crous'],
	transports: [
		'fluow', // veligo
	],
	voyages: [],
	sante: ['pharmacie'],
	revenus: [],
	remboursements: ['remb', 'remboursement'],
	mouvements_internes: [],
	impots: [],
	vie_quotidienne: [],
	amendes: [],
	voiture: ['tesla', 'ionity', 'izivia'],
	cadeaux: [],
	ecommerce: ['amazon', 'fnac', 'darty', 'cdiscount', 'boulanger'],
	vetements: [],
	maison: [],
	activites: [],
	banque: ['prlv ce', 'prlv bpce', 'bourso'],
	autres: [],
};
